line-length = 100
target-version = "py311"

[lint]
select = ["E", "F", "I", "B", "UP", "N", "RUF"]
ignore = ["B008"]

[lint.isort]
known-first-party = ["app"]

[format]
skip-magic-trailing-comma = false
quote-style = "double"
indent-style = "space"
line-ending = "lf"
